### PR TITLE
Added support for using authenticated redis server

### PR DESCRIPTION
**Pull request by dfezzie**
Used the BITMAPIST_REDIS_PASSWORD to provide support for an authenticated redis instance in the app config variables.

### CODE REVIEW

**Comment by frankV** [comment]
@dfezzie it looks like it failed on a PEP8 check. You can run the tests locally to make sure you're passing PEP8 and pyflakes.

I think @katie7r and I will want to write a test in for this before we merge - unless you want to tackle that?

**Comment by frankV** [comment]
Note that this will close #11

**Comment by dfezzie** [comment]
I can write a test for it, is there any specific way you want this done?

**Comment by frankV** [comment]
We will have to update Travis so that it creates a redis instance with a password. But if you want to write the tests for it

**Comment by dfezzie** [comment]
Definitely! I'll get those done.

**Comment by frankV** [comment]
@dfezzie thanks for fixing the test, we still need an authenticated Redis server test to close this. Happy to help you with it if you need.

**Pull request closed without merging**
